### ISSUE TITLE
Review comments - needs fixing!

### ISSUE THREAD

**Issue by Apollon77** [instalator/ioBroker.mercury#1]
Please check and fix the following issues:
* you need to clear ALL intervals and timeouts and close the serialport and such in unload, else compact mode will break (do you ever tested with compact mode and starting/stopping?)
* https://github.com/instalator/ioBroker.mercury/blob/master/main.js#L133 please use getObject to detect if an object exists and not getState!

**Comment by instalator** [comment]
> do you ever tested with compact mode and starting/stopping?
No

**Comment by Apollon77** [comment]
It would be great if you try that  ;-)

**Comment by Apollon77** [comment]
With adding the compact mode the "unload" method became essential in cleaning up all used resurces. This is not that relevant when it is running as normal process because the process exit will automatically clean all that ;-) But in compact mode it is just "the code that should stop working" and the db connection of the adapter gets killed too .... so if you still have stuff working you will flood the log with errors
