### ISSUE TITLE
add support IEC 61107 protocol for Энергомера CE102M

### ISSUE THREAD

**Issue by ximonline** [instalator/ioBroker.mercury#10]
Could you add support Энергомера CE102M by RS-485?
Product page description
http://www.energomera.ru/ru/products/meters/ce102mr5

Proticol description at page 68
http://www.energomera.ru/documentations/product/ce102m_re_full.pdf

Baud Rate: 9600
Data Bits: 7
Parity Check: even
Stop Bits: 1

**Comment by SanSanysch** [comment]
2 протокола в 1 драйвере? Мне кажется это будет неправильно. Правильно - писать отдельный драйвер для совершенно другого производителя (счётчика).

**Comment by instalator** [comment]
Вопрос не относится к драйверу Меркурия
