### ISSUE TITLE
Косяки и хотелки.

### ISSUE THREAD

**Issue by SanSanysch** [instalator/ioBroker.mercury#3]
Привет, Владимир!
Я тебе писал по электронке, обнаружил много недочётов в драйвере, но для начала - очень даже не плохо. Итак, косяки которые сразу бросаются в глаза: энергия за день, за год - всё 00, энергия по месяцам - не совпадает ни один показатель ни за один месяц, включая текущий, основные параметры - ток, мощность, коэф. мощности фазы 3 - всегда 0, коэф. мощности общий - 0, энергия, подписана "total" - складываешь актив и реактив - это не правильно, такой total никому не интересен. Это всё равно, что считать яйца + цыплята = ?
Надписи... (на вкус и цвет - товарища нет): убрать единицы измерения из полей значений, поскольку у тебя уже сейчас они не правильные: нужны Вт, а не кВт;
подписать имена, по возможности по русски. Сильно сомневаюсь, что немец или итальянец купит себе Меркурий. Знаю, требуют перевод.... сам уж решай.
Дальше хотелки или нуждилки: реализовать управление нагрузкой, слово состояния счётчика, время прибора и его корректировка ну и исправить "основные параметры": добавить реактивную и полную мощности. В общем, сравни с конфигураторм.
Остальное - роскошь! Не вижу смысла превращать драйвер в конфигуратор счётчиков. Мне кажется, даже энергия по месяцам не нужна. Я её смотрел за 5 лет 3 раза: 2 раза ради интереса и 1 - сравнил показания твоего драйвера и конфигуратора Инкотэкса. Из энергий только: общая (нарастающим итогом), за текущий день/месяц, за предыдущий день/месяц. Кому надо - сложат в архив и посчитают за 1,5 дня, неделю или 3 месяца.
Может быть, есть смысл, сделать в настройках выбор параметров что опрашивать? С разной периодичностью: энергию можно и раз в час (сутки), а U I P S Q Cosf - максимально часто.
Счётчик для испытаний есть? Помощь нужна?

**Comment by instalator** [comment]
У меня нет 3 фазного для тестов, если есть возможность то пробрось порт для теста.

**Comment by SanSanysch** [comment]
Доступ дал, проверил. Подробности отправил в письме.

**Comment by instalator** [comment]
Письмо не пишло. Напиши в телеграм @instalator

**Comment by SanSanysch** [comment]
переслал на mail.ru В телеге пока не регистрировался, у тебя вибер есть?

**Comment by instalator** [comment]
> переслал на mail.ru В телеге пока не регистрировался, у тебя вибер есть?
Нету

**Comment by instalator** [comment]
> энергия за день, за год - всё 00,
Вроде все отображает, что не так?
![image](https://user-images.githubusercontent.com/11523624/75133538-ce90aa00-570d-11ea-82fb-ea2bf7489903.png)

**Comment by instalator** [comment]
> основные параметры - ток, мощность, коэф. мощности фазы 3 - всегда 0, коэф. мощности общий - 0,

![image](https://user-images.githubusercontent.com/11523624/75133626-16afcc80-570e-11ea-8797-873bf952a32d.png)

**Comment by instalator** [comment]
Давай как ты драйвер переустановишь с удалением, явно что то у тебя не так.

**Comment by SanSanysch** [comment]
Дошло? У меня всё 00 и день и год. Чё за ...ня? Попробую

**Comment by SanSanysch** [comment]
Хотя ошибок при установке небыло

**Comment by instalator** [comment]
Установи с гитхаба

**Comment by SanSanysch** [comment]
С него и ставил. Один фиг 00
![Снимок экрана в 2020-02-24 10-18-39](https://user-images.githubusercontent.com/61174388/75134367-2370f800-56ef-11ea-88ad-9effae914d5d.png)

**Comment by instalator** [comment]
Удали счетчик и заново добавь

**Comment by SanSanysch** [comment]
У меня, при внесении счётчика: ввожу адрес, жму "Найти" - 0 эмоций. "Отмена" - счётчик уже есть, причём определяется правильно. А в объектах всё так же. Удалял - толку 0.

**Comment by SanSanysch** [comment]
Удалил, добавил. Теперь и без имени - нормально.

**Comment by instalator** [comment]
Проверь все, напиши что нужно изменить

**Comment by SanSanysch** [comment]
Так я ж в первом сообщении почти всё описал.

**Comment by instalator** [comment]
Закрываем?

**Comment by instalator** [comment]
Исправлено в 0.0.13, если возникнут вопросы, жду новый issue
