### ISSUE TITLE
Не верные вычисления мощности.

### ISSUE THREAD

**Issue by RnDim** [instalator/ioBroker.mercury#5]
Доброго времени суток. 
У меня на калькуляторе другие цифры выходят.
Например, по фазе 3 должно быть 2136 ват.
![изображение](https://user-images.githubusercontent.com/62649449/77532729-87314100-6ea6-11ea-919e-87c6c322279b.png)
![изображение](https://user-images.githubusercontent.com/62649449/77533639-4afee000-6ea8-11ea-858e-d05b14b837e0.png)
![изображение](https://user-images.githubusercontent.com/62649449/77533709-6e298f80-6ea8-11ea-8769-618487346164.png)
Драйвер переставлял с удалением.

**Comment by instalator** [comment]
Эти данные не расчетные, их отдает счётчик, а как он там считает и усредняет мне не известно.

**Comment by RnDim** [comment]
Раньше использовал скрипт от сюда -> https://forum.iobroker.net/topic/7779/%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82-%D0%B4%D0%BB%D1%8F-%D1%81%D1%87%D0%B5%D1%82%D1%87%D0%B8%D0%BA%D0%B0-%D0%BC%D0%B5%D1%80%D0%BA%D1%83%D1%80%D0%B8%D0%B9-230
Считалось все правильно.
Через конфигуратор пока нет возможности, это надо с ноутом на винде лезть.

**Comment by RnDim** [comment]
Лог
[log.txt](https://github.com/instalator/ioBroker.mercury/files/4381830/log.txt)

**Comment by SanSanysch** [comment]
Не переживайте! У меня такая же фигня и с мощностями и с токами. Драйвер ещё надо дорабатывать.

**Comment by instalator** [comment]
> Лог
> [log.txt](https://github.com/instalator/ioBroker.mercury/files/4381830/log.txt)

По логу у тебя потребление currentPhase3 { oldVal = 1 / newVal = 1.01 } 1 Ампер всего, мне не  нужен лог в котором нет ошибки

> У меня на калькуляторе другие цифры выходят.
> Например, по фазе 3 должно быть 2136 ват.

![image](https://user-images.githubusercontent.com/11523624/77646962-284bf480-6f98-11ea-82d8-cdbe821da345.png)
Какую мощность ты считал?

**Comment by instalator** [comment]
> Раньше использовал скрипт от сюда -> https://forum.iobroker.net/topic/7779/%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82-%D0%B4%D0%BB%D1%8F-%D1%81%D1%87%D0%B5%D1%82%D1%87%D0%B8%D0%BA%D0%B0-%D0%BC%D0%B5%D1%80%D0%BA%D1%83%D1%80%D0%B8%D0%B9-230
> Считалось все правильно.
> Через конфигуратор пока нет возможности, это надо с ноутом на винде лезть.

Команды запроса точно такие же как в скрипте
{code: 0x08, cmd: [0x16, 0x00], desc: 'Мощность по фазам', func: f.powerPhase},
                {code: 0x08, cmd: [0x16, 0x11], desc: 'Напряжение по фазам', func: f.voltagePhase},
                {code: 0x08, cmd: [0x16, 0x21], desc: 'Ток по фазам', func: f.currentPhase},
                {code: 0x08, cmd: [0x16, 0x30], desc: 'Коэффициент мощности по фазам', func: f.cosf}

**Comment by instalator** [comment]
0.0.12

**Comment by RnDim** [comment]
Пардон, не доглядел что потребление минимально.
Новый лог.
[log.txt](https://github.com/instalator/ioBroker.mercury/files/4388449/log.txt)

**Comment by RnDim** [comment]
Version 0.0.13
[log.txt](https://github.com/instalator/ioBroker.mercury/files/4395750/log.txt)
Запускается, зеленый и дальше стоит, в логе видно.
