### ISSUE TITLE
Version 0.0.13

### ISSUE THREAD

**Issue by RnDim** [instalator/ioBroker.mercury#7]
Version 0.0.13
[log.txt](https://github.com/instalator/ioBroker.mercury/files/4395913/log.txt)
Запускается, зеленый и дальше стоит, в логе видно.

**Comment by instalator** [comment]
Обнови с гита

**Comment by RnDim** [comment]
Вроде все ок, наблюдаю.
Добавились еще параметры
![изображение](https://user-images.githubusercontent.com/62649449/77830001-8c0c2400-7136-11ea-9d2c-c85c16ac0132.png)
Спасибо!!!

**Comment by RnDim** [comment]
Нагрузил
![изображение](https://user-images.githubusercontent.com/62649449/77830147-92e76680-7137-11ea-9e57-cee0966d4399.png)

**Comment by instalator** [comment]
> Нагрузил
> ![изображение](https://user-images.githubusercontent.com/62649449/77830147-92e76680-7137-11ea-9e57-cee0966d4399.png)

т.е. все корректно?

**Comment by RnDim** [comment]
Вроде корректно.
Бегло, не понял где суточный расход. Хотя можно и вычислить.

**Comment by RnDim** [comment]
![изображение](https://user-images.githubusercontent.com/62649449/78175179-1ddf9e00-7463-11ea-904a-f33dcef5596e.png)
Получается суточный тут -> mercury.0.2687323.Day.TotalEnergyActivePlus
